Repository bounswe/bounswe2020group5, pull requests merged in 2020-05, with the labels that each got.

#61 Ismet
  practice-app/back-end/package-lock.json
  practice-app/back-end/package.json
  practice-app/back-end/routes/keys.js
  practice-app/back-end/routes/twittercomments.js
Labels: Help Please!!, Priority: Medium, Status: In Progress, enhancement

#62 Searching tweets a vendor is mentioned by another user
  practice-app/back-end/app.js
  practice-app/back-end/routes/filter_user_tweets.js
Labels: Priority: Medium, Status: Needs Review, help wanted

#63 Search trend product
  practice-app/back-end/app.js
  practice-app/back-end/package-lock.json
  practice-app/back-end/package.json
  practice-app/back-end/routes/keys.js
  practice-app/back-end/routes/searchtrendforproduct.js
Labels: Priority: Medium, Status: Needs Review, help wanted

#83 Front-end implementation of showfollowers.js is completed.
  .DS_Store
  package-lock.json
  practice-app/.DS_Store
  practice-app/back-end/.DS_Store
  practice-app/back-end/routes/.Rhistory
  practice-app/back-end/routes/keys.js
  practice-app/front-end/src/App.js
  practice-app/front-end/src/Components/GetComments.js
  practice-app/front-end/src/Components/ShowFollowers.js
Labels: Homework, Status: Completed, Status: Needs Review

#68 Mongodb
  practice-app/back-end/app.js
  practice-app/back-end/data/mongod.lock
  practice-app/back-end/package-lock.json
  practice-app/back-end/package.json
  practice-app/back-end/routes/database.js
  practice-app/back-end/routes/index.js
  practice-app/back-end/views/newproduct.jade
  practice-app/back-end/views/productlist.jade
Labels: Priority: Medium

#69 Vendor trends
  practice-app/back-end/app.js
  practice-app/back-end/package-lock.json
  practice-app/back-end/routes/keys.js
  practice-app/back-end/routes/searchtrendforvendor.js
Labels: Priority: Medium, Status: Needs Review, help wanted

#96 Testcase for filter_user_tweets.js
  practice-app/back-end/test/test-filter_user_tweets.js
Labels: Priority: High, Status: Needs Review, help wanted

#93 vendortweets file is added
  practice-app/back-end/app.js
  practice-app/back-end/routes/vendortweets.js
Labels: Priority: Medium, Status: Needs Review
